export default {
    home: "/",
    platform: "/platform",
    about: "/about",
    contacts: "/contacts",
    specialists: "/specialists",
    singleSpecialist: "/specialists/:id",
    article: "/article/:article",
    paidArticle: "/article/:paid-article",
    test: "/test",
    policyPrivacy: "/policy-privacy",
    login: "/login",
    restorePassword: "/restore-password",
    profile: "/profile",
}